### ISSUE TITLE
Temperature conversion: Keine Fehlermeldung wenn der Conversion Type größer 6 ist

### ISSUE THREAD

**Issue by nschuette** [malte9202/python#1]
**IST**
Gebe ich bei der Auswahl des Typs eine Zahl an die größer als 6 ist, kommt aktuell keine Fehlermeldung.

**SOLL**
Fehlermeldung wird angezeigt.

**Comment by malte9202** [comment]
sollte mit dem letzten commit gefixt sein:

`    while convert_type not in [1,2,3,4,5,6]:
        try:
            convert_type = int(input("Choose a type of conversion by entering a number from 1 to 6: "))
            raise ValueError  # raise error to print error message from below 
        except ValueError:
            print("Invalid input. Enter a number from 1 to 6 to choose the type of conversion")
    return convert_type`

input der nicht 1,2,3,4,5,6 ist raised jetzt einen value error und gibt die meldung aus
